<?php

namespace mesusah\crafttryhackme\migrations;

use Craft;
use craft\db\Migration;

/**
 * m231028_150541_insert_countries migration.
 */
class m231028_150541_insert_countries extends Migration
{
    /**
     * @inheritdoc
     */
    public function safeUp(): bool
    {
        $fields = [
            'handle',
            'name',
        ];

        $countries = [
            [strtolower('AF'), 'Afghanistan'],
            [strtolower('AX'), 'Aland Islands'],
            [strtolower('AL'), 'Albania'],
            [strtolower('DZ'), 'Algeria'],
            [strtolower('AS'), 'American Samoa'],
            [strtolower('AD'), 'Andorra'],
            [strtolower('AO'), 'Angola'],
            [strtolower('AI'), 'Anguilla'],
            [strtolower('AQ'), 'Antarctica'],
            [strtolower('AG'), 'Antigua And Barbuda'],
            [strtolower('AR'), 'Argentina'],
            [strtolower('AM'), 'Armenia'],
            [strtolower('AW'), 'Aruba'],
            [strtolower('AU'), 'Australia'],
            [strtolower('AT'), 'Austria'],
            [strtolower('AZ'), 'Azerbaijan'],
            [strtolower('BS'), 'Bahamas'],
            [strtolower('BH'), 'Bahrain'],
            [strtolower('BD'), 'Bangladesh'],
            [strtolower('BB'), 'Barbados'],
            [strtolower('BY'), 'Belarus'],
            [strtolower('BE'), 'Belgium'],
            [strtolower('BZ'), 'Belize'],
            [strtolower('BJ'), 'Benin'],
            [strtolower('BM'), 'Bermuda'],
            [strtolower('BT'), 'Bhutan'],
            [strtolower('BO'), 'Bolivia'],
            [strtolower('BA'), 'Bosnia And Herzegovina'],
            [strtolower('BW'), 'Botswana'],
            [strtolower('BV'), 'Bouvet Island'],
            [strtolower('BR'), 'Brazil'],
            [strtolower('IO'), 'British Indian Ocean Territory'],
            [strtolower('BN'), 'Brunei Darussalam'],
            [strtolower('BG'), 'Bulgaria'],
            [strtolower('BF'), 'Burkina Faso'],
            [strtolower('BI'), 'Burundi'],
            [strtolower('KH'), 'Cambodia'],
            [strtolower('CM'), 'Cameroon'],
            [strtolower('CA'), 'Canada'],
            [strtolower('CV'), 'Cape Verde'],
            [strtolower('KY'), 'Cayman Islands'],
            [strtolower('CF'), 'Central African Republic'],
            [strtolower('TD'), 'Chad'],
            [strtolower('CL'), 'Chile'],
            [strtolower('CN'), 'China'],
            [strtolower('CX'), 'Christmas Island'],
            [strtolower('CC'), 'Cocos (Keeling) Islands'],
            [strtolower('CO'), 'Colombia'],
            [strtolower('KM'), 'Comoros'],
            [strtolower('CG'), 'Congo'],
            [strtolower('CD'), 'Congo, Democratic Republic'],
            [strtolower('CK'), 'Cook Islands'],
            [strtolower('CR'), 'Costa Rica'],
            [strtolower('CI'), 'Cote D\'Ivoire'],
            [strtolower('HR'), 'Croatia'],
            [strtolower('CU'), 'Cuba'],
            [strtolower('CY'), 'Cyprus'],
            [strtolower('CZ'), 'Czech Republic'],
            [strtolower('DK'), 'Denmark'],
            [strtolower('DJ'), 'Djibouti'],
            [strtolower('DM'), 'Dominica'],
            [strtolower('DO'), 'Dominican Republic'],
            [strtolower('EC'), 'Ecuador'],
            [strtolower('EG'), 'Egypt'],
            [strtolower('SV'), 'El Salvador'],
            [strtolower('GQ'), 'Equatorial Guinea'],
            [strtolower('ER'), 'Eritrea'],
            [strtolower('EE'), 'Estonia'],
            [strtolower('ET'), 'Ethiopia'],
            [strtolower('FK'), 'Falkland Islands (Malvinas)'],
            [strtolower('FO'), 'Faroe Islands'],
            [strtolower('FJ'), 'Fiji'],
            [strtolower('FI'), 'Finland'],
            [strtolower('FR'), 'France'],
            [strtolower('GF'), 'French Guiana'],
            [strtolower('PF'), 'French Polynesia'],
            [strtolower('TF'), 'French Southern Territories'],
            [strtolower('GA'), 'Gabon'],
            [strtolower('GM'), 'Gambia'],
            [strtolower('GE'), 'Georgia'],
            [strtolower('DE'), 'Germany'],
            [strtolower('GH'), 'Ghana'],
            [strtolower('GI'), 'Gibraltar'],
            [strtolower('GR'), 'Greece'],
            [strtolower('GL'), 'Greenland'],
            [strtolower('GD'), 'Grenada'],
            [strtolower('GP'), 'Guadeloupe'],
            [strtolower('GU'), 'Guam'],
            [strtolower('GT'), 'Guatemala'],
            [strtolower('GG'), 'Guernsey'],
            [strtolower('GN'), 'Guinea'],
            [strtolower('GW'), 'Guinea-Bissau'],
            [strtolower('GY'), 'Guyana'],
            [strtolower('HT'), 'Haiti'],
            [strtolower('HM'), 'Heard Island & Mcdonald Islands'],
            [strtolower('VA'), 'Holy See (Vatican City State)'],
            [strtolower('HN'), 'Honduras'],
            [strtolower('HK'), 'Hong Kong'],
            [strtolower('HU'), 'Hungary'],
            [strtolower('IS'), 'Iceland'],
            [strtolower('IN'), 'India'],
            [strtolower('ID'), 'Indonesia'],
            [strtolower('IR'), 'Iran, Islamic Republic Of'],
            [strtolower('IQ'), 'Iraq'],
            [strtolower('IE'), 'Ireland'],
            [strtolower('IM'), 'Isle Of Man'],
            [strtolower('IL'), 'Israel'],
            [strtolower('IT'), 'Italy'],
            [strtolower('JM'), 'Jamaica'],
            [strtolower('JP'), 'Japan'],
            [strtolower('JE'), 'Jersey'],
            [strtolower('JO'), 'Jordan'],
            [strtolower('KZ'), 'Kazakhstan'],
            [strtolower('KE'), 'Kenya'],
            [strtolower('KI'), 'Kiribati'],
            [strtolower('KR'), 'Korea'],
            [strtolower('KW'), 'Kuwait'],
            [strtolower('KG'), 'Kyrgyzstan'],
            [strtolower('LA'), 'Lao People\'s Democratic Republic'],
            [strtolower('LV'), 'Latvia'],
            [strtolower('LB'), 'Lebanon'],
            [strtolower('LS'), 'Lesotho'],
            [strtolower('LR'), 'Liberia'],
            [strtolower('LY'), 'Libyan Arab Jamahiriya'],
            [strtolower('LI'), 'Liechtenstein'],
            [strtolower('LT'), 'Lithuania'],
            [strtolower('LU'), 'Luxembourg'],
            [strtolower('MO'), 'Macao'],
            [strtolower('MK'), 'Macedonia'],
            [strtolower('MG'), 'Madagascar'],
            [strtolower('MW'), 'Malawi'],
            [strtolower('MY'), 'Malaysia'],
            [strtolower('MV'), 'Maldives'],
            [strtolower('ML'), 'Mali'],
            [strtolower('MT'), 'Malta'],
            [strtolower('MH'), 'Marshall Islands'],
            [strtolower('MQ'), 'Martinique'],
            [strtolower('MR'), 'Mauritania'],
            [strtolower('MU'), 'Mauritius'],
            [strtolower('YT'), 'Mayotte'],
            [strtolower('MX'), 'Mexico'],
            [strtolower('FM'), 'Micronesia, Federated States Of'],
            [strtolower('MD'), 'Moldova'],
            [strtolower('MC'), 'Monaco'],
            [strtolower('MN'), 'Mongolia'],
            [strtolower('ME'), 'Montenegro'],
            [strtolower('MS'), 'Montserrat'],
            [strtolower('MA'), 'Morocco'],
            [strtolower('MZ'), 'Mozambique'],
            [strtolower('MM'), 'Myanmar'],
            [strtolower('NA'), 'Namibia'],
            [strtolower('NR'), 'Nauru'],
            [strtolower('NP'), 'Nepal'],
            [strtolower('NL'), 'Netherlands'],
            [strtolower('AN'), 'Netherlands Antilles'],
            [strtolower('NC'), 'New Caledonia'],
            [strtolower('NZ'), 'New Zealand'],
            [strtolower('NI'), 'Nicaragua'],
            [strtolower('NE'), 'Niger'],
            [strtolower('NG'), 'Nigeria'],
            [strtolower('NU'), 'Niue'],
            [strtolower('NF'), 'Norfolk Island'],
            [strtolower('MP'), 'Northern Mariana Islands'],
            [strtolower('NO'), 'Norway'],
            [strtolower('OM'), 'Oman'],
            [strtolower('PK'), 'Pakistan'],
            [strtolower('PW'), 'Palau'],
            [strtolower('PS'), 'Palestinian Territory, Occupied'],
            [strtolower('PA'), 'Panama'],
            [strtolower('PG'), 'Papua New Guinea'],
            [strtolower('PY'), 'Paraguay'],
            [strtolower('PE'), 'Peru'],
            [strtolower('PH'), 'Philippines'],
            [strtolower('PN'), 'Pitcairn'],
            [strtolower('PL'), 'Poland'],
            [strtolower('PT'), 'Portugal'],
            [strtolower('PR'), 'Puerto Rico'],
            [strtolower('QA'), 'Qatar'],
            [strtolower('RE'), 'Reunion'],
            [strtolower('RO'), 'Romania'],
            [strtolower('RU'), 'Russian Federation'],
            [strtolower('RW'), 'Rwanda'],
            [strtolower('BL'), 'Saint Barthelemy'],
            [strtolower('SH'), 'Saint Helena'],
            [strtolower('KN'), 'Saint Kitts And Nevis'],
            [strtolower('LC'), 'Saint Lucia'],
            [strtolower('MF'), 'Saint Martin'],
            [strtolower('PM'), 'Saint Pierre And Miquelon'],
            [strtolower('VC'), 'Saint Vincent And Grenadines'],
            [strtolower('WS'), 'Samoa'],
            [strtolower('SM'), 'San Marino'],
            [strtolower('ST'), 'Sao Tome And Principe'],
            [strtolower('SA'), 'Saudi Arabia'],
            [strtolower('SN'), 'Senegal'],
            [strtolower('RS'), 'Serbia'],
            [strtolower('SC'), 'Seychelles'],
            [strtolower('SL'), 'Sierra Leone'],
            [strtolower('SG'), 'Singapore'],
            [strtolower('SK'), 'Slovakia'],
            [strtolower('SI'), 'Slovenia'],
            [strtolower('SB'), 'Solomon Islands'],
            [strtolower('SO'), 'Somalia'],
            [strtolower('ZA'), 'South Africa'],
            [strtolower('GS'), 'South Georgia And Sandwich Isl.'],
            [strtolower('ES'), 'Spain'],
            [strtolower('LK'), 'Sri Lanka'],
            [strtolower('SD'), 'Sudan'],
            [strtolower('SR'), 'Suriname'],
            [strtolower('SJ'), 'Svalbard And Jan Mayen'],
            [strtolower('SZ'), 'Swaziland'],
            [strtolower('SE'), 'Sweden'],
            [strtolower('CH'), 'Switzerland'],
            [strtolower('SY'), 'Syrian Arab Republic'],
            [strtolower('TW'), 'Taiwan'],
            [strtolower('TJ'), 'Tajikistan'],
            [strtolower('TZ'), 'Tanzania'],
            [strtolower('TH'), 'Thailand'],
            [strtolower('TL'), 'Timor-Leste'],
            [strtolower('TG'), 'Togo'],
            [strtolower('TK'), 'Tokelau'],
            [strtolower('TO'), 'Tonga'],
            [strtolower('TT'), 'Trinidad And Tobago'],
            [strtolower('TN'), 'Tunisia'],
            [strtolower('TR'), 'Turkey'],
            [strtolower('TM'), 'Turkmenistan'],
            [strtolower('TC'), 'Turks And Caicos Islands'],
            [strtolower('TV'), 'Tuvalu'],
            [strtolower('UG'), 'Uganda'],
            [strtolower('UA'), 'Ukraine'],
            [strtolower('AE'), 'United Arab Emirates'],
            [strtolower('GB'), 'United Kingdom'],
            [strtolower('US'), 'United States'],
            [strtolower('UM'), 'United States Outlying Islands'],
            [strtolower('UY'), 'Uruguay'],
            [strtolower('UZ'), 'Uzbekistan'],
            [strtolower('VU'), 'Vanuatu'],
            [strtolower('VE'), 'Venezuela'],
            [strtolower('VN'), 'Viet Nam'],
            [strtolower('VG'), 'Virgin Islands, British'],
            [strtolower('VI'), 'Virgin Islands, U.S.'],
            [strtolower('WF'), 'Wallis And Futuna'],
            [strtolower('EH'), 'Western Sahara'],
            [strtolower('YE'), 'Yemen'],
            [strtolower('ZM'), 'Zambia'],
            [strtolower('ZW'), 'Zimbabwe'],
        ];

        $this->batchInsert('{{%tryhackme_country}}', $fields, $countries);
        return true;
    }

    /**
     * @inheritdoc
     */
    public function safeDown(): bool
    {
        $this->delete('{{%tryhackme_country}}');
        return true;
    }
}
